config/routes.rb
Probset3::Application.routes.draw do
  match '/messages/create/:from/:to' => "messages#create" , :as=>"createmessage" 
  match '/messages/private/:from/:to' => "messages#showprivatechat" , :as=>"showprivatechat" 
  match '/messages/create/:from' => "seats#createglobalmessage", :as=>"createglobalmessage"
  

  resources :seats
  resources :messages

	resources :users
	resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/seats/sit/:id' => 'seats#sit'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # POST /messages
  # POST /messages.xml
  def createglobalmessage
    @seats = Seat.all
    @message = Message.new
    @message.message = params[:g_message]
    @message.user_id_from = params[:from]
    @message.user_id_to = nil
    @message.save
   
    @messages = Message.find_all_by_user_id_to(nil)
    
    @messages.each do |m|
      @gconversation = "#{@gconversation}\n#{m.created_at.localtime}:#{m.user_id_from}:#{m.message}"
    end

    respond_to do |format|
        format.html { render :action => "index.html.erb" }
    end
  end

  # POST /messages
  # POST /messages.xml
  def showprivatechat 
    @messages =  Message.find_all_by_user_id_to(params[:to])  
    
    @messages.each do |m|   
        @conversation = "#{@conversation}\n#{m.created_at.localtime}:#{m.user_id_from}:#{m.message}"
    end
    
    respond_to do |format|
      format.html # showprivatechat.html.erb
      format.xml  { render :xml => @message }
    end
  end
  
  
  # GET /messages
  # GET /messages.xml
  def index
    @messages = Message.all
    #fromID = params[:from]
    #toId = params[:to]
    #@conversation = Message.find_all_by_user_id_from_and_user_id_to(fromID, toID)
    @conversation = Message.all
    #Message.all.each {|m| @conversation << m.message if m.nil?}
    #@conversation = Message.first.message


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new
    respond_to do |format|
      format.html #{ redirect_to (messages_url) } # index.html.erb #  new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new
    @message.message = params[:message]
    @message.user_id_from = params[:from]
    @message.user_id_to = params[:to]

    respond_to do |format|
      if @message.save
        format.html { redirect_to(showprivatechat_path) }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Chat View</h1>

<br />
<table border=1>
  <tr>
    <th>Seat</th>
  </tr>
  <tr>
    <td>
      <%= form_tag ('/messages/create') do %>

        <%= text_area_tag(:message_output, @conversation, :size=>"75x10", :readonly=>"readonly") %>
        <br/>
        <%= text_area_tag(:message, "", :size=>"75x10") %> 
      
      <div class="actions">
        <%= submit_tag(:Send) %>
      </div>
     <% end %>
    </td>
  </tr>
</table>


 <%= link_to 'Seating Chart', seats_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/messages/showprivatechat.html.erb
<h1>Chat View</h1>

<br />

<table border=1>
  <tr>
    <th>Seat <%= params[:to] %></th>
  </tr>
  <tr>
    <td>
      <%= form_tag ("/messages/create/#{params[:from]}/#{params[:to]}") do %>

        <%= text_area_tag(:message_output, @conversation, :size=>"75x10", :readonly=>"readonly") %>
        <br/>
        <%= text_area_tag(:message, "", :size=>"75x10") %> 
      
      <div class="actions">
        <%= submit_tag(:Send) %>
      </div>
     <% end %>
    </td>
  </tr>
</table>


 <%= link_to 'Seating Chart', seats_path %>