config/routes.rb
Probset3::Application.routes.draw do
  match '/messages/create/:from/:to' => "messages#create" , :as=>"createmessage" 
  match '/messages/private/:from/:to' => "messages#showprivatechat" , :as=>"showprivatechat" 
  match '/messages/create/:from' => "seats#createglobalmessage", :as=>"createglobalmessage"
  

  resources :seats
  resources :messages

	resources :users
	resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/seats/sit/:id' => 'seats#sit'

end

app/models/seat.rb
class Seat < ActiveRecord::Base
   belongs_to :user
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController

  def createglobalmessage
    @counter = 0
    @seats = Seat.all

    @message = Message.new
    @message.message = params[:g_message]
    @message.user_id_from = params[:from]
    @message.user_id_to = nil

    @message.save
     
 #   @messages = Message.find_all_by_user_id_to(nil)
  #   @messages.each do |m|
  #    @gconversation = "#{@gconversation}\n#{m.created_at.localtime}:#{m.user_id_from}:#{m.message}"
  #  end

    respond_to do |format|
        format.html {redirect_to(seats_url)} #{ render :action => "index.html.erb" }
    end
  end


  # GET /seats
  # GET /seats.xml
  def index
   @counter = 0
    @seats = Seat.all

    @messages = Message.find_all_by_user_id_to(nil)
    @messages.each do |m|
      @gconversation = "#{@gconversation}\n#{m.created_at.localtime}:#{m.user_id_from}"
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @seats }
    end
  end

  # GET /seats/1
  # GET /seats/1.xml
  def show
    @seat = Seat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @seat }
    end
  end

  # GET /seats/new
  # GET /seats/new.xml
  def new
    @seat = Seat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @seat }
    end
  end

  # GET /seats/1/edit
  def edit
    @seat = Seat.find(params[:id])
  end

  # POST /seats
  # POST /seats.xml
  def create
    @seat = Seat.new(params[:seat])

    respond_to do |format|
      if @seat.save
        format.html { redirect_to(@seat, :notice => 'Seat was successfully created.') }
        format.xml  { render :xml => @seat, :status => :created, :location => @seat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /seats/1
  # PUT /seats/1.xml
  def update
    @seat = Seat.find(params[:id])

    respond_to do |format|
      if @seat.update_attributes(params[:seat])
        format.html { redirect_to(@seat, :notice => 'Seat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.xml
  def destroy
    @seat = Seat.find(params[:id])
    @seat.destroy

    respond_to do |format|
      format.html { redirect_to(seats_url) }
      format.xml  { head :ok }
    end
  end

  # PUT /seats/1
  # PUT /seats/1.xml
  def sit
    @seat = Seat.find(params[:id])
    
    @seat.user_id= current_user
    @seat.save



    respond_to do |format|
      format.html {redirect_to(seats_url)}
      format.xml  { render :xml => @seats }
    end

 end
end

app/helpers/seat_helper.rb
module SeatHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render 'form' %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<h1>Listing seats</h1>




<div id="divMain">  
<div id="divMainContent">


<div class="seating">Seating Chart
<hr/>

<table>
<tbody>
<tr><th colspan="8">
	<div class="ProfSeat">
	<p class="SeatTakenHeading">Professor</p>
	<a title="Seat Reserved for Professor" href=""><p class="SeatDetail"><strong>Prof. Avery</strong> </p></a> </div>
</th></tr>
<tr>
    <% @seats.each do |seat| %>
       <% if @counter > 7  %>
         <% @counter=0 %>
	  </tr><tr>
	<% end %>
	<td>
		<% if seat.user  %><div class="SeatTaken">
		<p class="SeatTakenHeading"><%= seat.id%></p>
		<a title="Seat Taken By: <%= seat.user.fname %>" href=""><p class="SeatDetail"><strong><%= seat.user.fname %> <%= seat.user.lname %> </strong> </p></a>
		<a title="Chat with <%= seat.user.fname %>" href=""><p class="SeatDetail">Chat</p></a> </div>
		<% else %>
		<div class="SeatOpen">
		<p class="SeatOpenHeading"><%= seat.id%></p>
		<p class="SeatDetail"><a title="Occupy Seat:<%= seat.id%>" href=""><%= button_to "Sit", :action => "sit", :id => seat.id %> </p></a>
		</div>
		<% end %> 
	</td>
    <% @counter+=1 %>
    <% end %>
</tbody>
</table> <br/><br/>
</div>


<h1>Classroom Chat Box</h1><br/>
<%= form_tag ("/messages/create/1") do %>
  <p> <%= @gconversation %> </p>
  <%= text_area_tag(:g_message_output, @gconversation, :size=>"75x10", :readonly=>"readonly") %>
  <br/>
  <%= text_area_tag(:g_message, "", :size=>"75x10") %>
  
  <div class="actions">
    <%= submit_tag(:Send) %>
  </div>
<% end %>


<br/>
<br/>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @seat.user_id %>
</p>


<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>