config/routes.rb
Probset3::Application.routes.draw do
  match '/messages/create/:from/:to' => "messages#create" , :as=>"createmessage" 
  match '/messages/private/:from/:to' => "messages#showprivatechat" , :as=>"showprivatechat" 
  match '/messages/create/:from' => "seats#createglobalmessage", :as=>"createglobalmessage"
  

  resources :seats
  resources :messages

	resources :users
	resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/seats/sit/:id' => 'seats#sit'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CS-408 Class Seating Chart</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <link rel="stylesheet" href="ChartStylesheet.css" type="text/css" />
</head>
<body>
  <div id="header">
    <h1><%= link_to "Welcome to CS-408!", users_path %></h1>
    <div id="user_bar">
      <% if logged_in? %>
        <%= link_to "Edit User", edit_user_path(current_user) %> |
        <%= link_to "Logout", logout_path %>
      <% else %>
        <%= link_to "New User", new_user_path %>
        <%= link_to "Login", login_path %>
      <% end %>
    </div>
  </div>
  <div id="main">					  
    <%= content_tag(:p, notice, :class => 'notice') if notice.present? %>
    <%= content_tag(:p, alert, :class => 'alert') if alert.present? %>
    <%= yield %>
  </div>
  <div id="footer">
    An interactive class seating chart.
  </div>
</body>
</html>